//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:16:26 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.plcopen.org/xml/tc6_0201", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package openplc.xml;
