//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:16:26 AM MSK 
//


package openplc.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pouType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pouType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="function"/&gt;
 *     &lt;enumeration value="functionBlock"/&gt;
 *     &lt;enumeration value="program"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "pouType")
@XmlEnum
public enum PouType {

    @XmlEnumValue("function")
    FUNCTION("function"),
    @XmlEnumValue("functionBlock")
    FUNCTION_BLOCK("functionBlock"),
    @XmlEnumValue("program")
    PROGRAM("program");
    private final String value;

    PouType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PouType fromValue(String v) {
        for (PouType c: PouType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
