//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:16:26 AM MSK 
//


package openplc.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for storageModifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="storageModifierType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="set"/&gt;
 *     &lt;enumeration value="reset"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "storageModifierType")
@XmlEnum
public enum StorageModifierType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("set")
    SET("set"),
    @XmlEnumValue("reset")
    RESET("reset");
    private final String value;

    StorageModifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StorageModifierType fromValue(String v) {
        for (StorageModifierType c: StorageModifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
