//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 01:16:26 AM MSK 
//


package openplc.xml;

import javax.xml.bind.annotation.*;


/**
 * List of variable declarations that share the same memory attributes (CONSTANT, RETAIN, NON_RETAIN, PERSISTENT)
 * 
 * <p>Java class for varList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="varList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.plcopen.org/xml/tc6_0201}varListPlain"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="constant" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="retain" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="nonretain" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="persistent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="nonpersistent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "varList")
@XmlSeeAlso({
    Project.Types.Pous.Pou.Interface.LocalVars.class,
    Project.Types.Pous.Pou.Interface.TempVars.class,
    Project.Types.Pous.Pou.Interface.InputVars.class,
    Project.Types.Pous.Pou.Interface.OutputVars.class,
    Project.Types.Pous.Pou.Interface.InOutVars.class,
    Project.Types.Pous.Pou.Interface.ExternalVars.class,
    Project.Types.Pous.Pou.Interface.GlobalVars.class
})
public class VarList
    extends VarListPlain
{

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "constant")
    protected Boolean constant;
    @XmlAttribute(name = "retain")
    protected Boolean retain;
    @XmlAttribute(name = "nonretain")
    protected Boolean nonretain;
    @XmlAttribute(name = "persistent")
    protected Boolean persistent;
    @XmlAttribute(name = "nonpersistent")
    protected Boolean nonpersistent;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConstant() {
        if (constant == null) {
            return false;
        } else {
            return constant;
        }
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConstant(Boolean value) {
        this.constant = value;
    }

    /**
     * Gets the value of the retain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRetain() {
        if (retain == null) {
            return false;
        } else {
            return retain;
        }
    }

    /**
     * Sets the value of the retain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetain(Boolean value) {
        this.retain = value;
    }

    /**
     * Gets the value of the nonretain property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNonretain() {
        if (nonretain == null) {
            return false;
        } else {
            return nonretain;
        }
    }

    /**
     * Sets the value of the nonretain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonretain(Boolean value) {
        this.nonretain = value;
    }

    /**
     * Gets the value of the persistent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPersistent() {
        if (persistent == null) {
            return false;
        } else {
            return persistent;
        }
    }

    /**
     * Sets the value of the persistent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPersistent(Boolean value) {
        this.persistent = value;
    }

    /**
     * Gets the value of the nonpersistent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNonpersistent() {
        if (nonpersistent == null) {
            return false;
        } else {
            return nonpersistent;
        }
    }

    /**
     * Sets the value of the nonpersistent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNonpersistent(Boolean value) {
        this.nonpersistent = value;
    }

}
